<div class="title"><h1><?=$this->module_name;?></h1></div>
<div class="row-fluid">
    <div class="span12">
        <div class="widget">
            <table width="100%" cellspacing="0" cellpadding="0" class="tableStatic adm" id="sortable">
                <thead>
                <tr>
                    <th width="20%">Nazwa</th>
                    <th width="30%">Tekst</th>
                    <th width="20%">Powierzchnia</th>
                    <th width="20%">Obrazek</th>
                    <th width="10%"></th>
                </tr>
                </thead>
                <tbody class="content">
                <?php foreach($this->lista as $pozycja) : ?>
                    <tr id="recordsArray_<?=$this->escape($pozycja->id);?>">
                        <td><?=$this->escape($pozycja->name);?></td>
                        <td><?=$this->escape($pozycja->text);?></td>
                        <td><?=$this->escape($pozycja->area);?></td>
                        <td ><img src="<?=$this->baseUrl();?>/files/showrooms/<?=$this->escape($pozycja->file);?>" alt="<?=$this->escape($pozycja->name);?>" style="width: 300px"></td>
                        <td class="right">
                            <a href="<?=$this->baseUrl();?>/admin/<?=$this->module;?>/edit/id/<?=$this->escape($pozycja->id);?>/" class="actionBtn tip btnEdit" title="Edytuj"></a>
                            <a href="<?=$this->baseUrl();?>/admin/<?=$this->module;?>/delete/id/<?=$this->escape($pozycja->id);?>/" class="actionBtn tip btnDelete confirm" title="Usuń"></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
            <div class="table-footer">
                <a href="<?=$this->baseUrl();?>/admin/<?=$this->module;?>/add/" class="button greyishBtn">Dodaj</a>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">$(document).ready(function(){$("#sortable tbody.content").sortuj('<?=$this->baseUrl();?>/admin/<?=$this->module;?>/sort/');});</script>