<div class="title"><h1><?=$this->inwestycja->nazwa;?> - <?=$this->controlname;?></h1></div>
<div class="row-fluid">
    <div class="span12">
        <ul class="nav nav-tabs none">
            <li><a href="<?=$this->baseUrl();?>/admin/inwestycje/"><span class="fa i-lista"></span>Lista inwestycji</a></li>
            <li><a href="<?=$this->baseUrl();?>/admin/inwestycje/show/id/<?=$this->inwestycja->id;?>/"><span class="fa i-inwest"></span><?=$this->inwestycja->nazwa;?></a></li>
            <li><a href="<?=$this->baseUrl();?>/admin/inwestycje-plan/add/id/<?=$this->inwestycja->id;?>/"><span class="fa i-image"></span>Plan</a></li>
            <li><a href="<?=$this->baseUrl();?>/admin/inwestycje-atuty/show/id/<?=$this->inwestycja->id;?>/"><span class="fa i-atuty"></span>Atuty</a></li>
            <li><a href="<?=$this->baseUrl();?>/admin/inwestycje-slider/show/id/<?=$this->inwestycja->id;?>/"><span class="fa i-image"></span>Slider</a></li>
            <li class="active"><span class="fa i-news"></span>Dziennik inwestycji</li>
        </ul>

        <div class="widget">
            <div class="table-header"><form action="" id="filter-form">
                    <label>
                        <span>Szukaj:</span><input type="text" size="30" maxlength="30" value="" id="filter" name="filter" />
                    </label>
                </form></div>
            <table width="100%" cellspacing="0" cellpadding="0" class="tableStatic adm" id="sortable">
                <thead>
                <tr>
                    <th width="70%">Tytuł</th>
                    <th width="5%" class="center">Status</th>
                    <th width="10%">Data</th>
                    <th width="10%"></th>
                    <?php if($this->canbetranslate){?><th width="5%"></th><?php } ?>
                </tr>
                </thead>
                <tbody class="content">
                <?php foreach($this->lista as $pozycja) : ?>
                    <tr id="recordsArray_<?= $this->escape($pozycja->id);?>">
                        <td><?=$this->escape($pozycja->tytul);?></td>
                        <td class="center"><?=status($pozycja->status);?></td>
                        <td><?=$this->escape($pozycja->data);?></td>
                        <td class="right">
                            <a href="<?=$this->baseUrl();?>/admin/inwestycje-dziennik/edit/id/<?=$this->escape($pozycja->id);?>/inwest/<?=$this->inwestycja->id;?>/" class="actionBtn tip btnEdit" title="Edytuj"></a>
                            <a href="<?=$this->baseUrl();?>/admin/inwestycje-dziennik/delete/id/<?=$this->escape($pozycja->id);?>/inwest/<?=$this->inwestycja->id;?>/" class="actionBtn tip btnDelete confirm" title="Usuń"></a>
                        </td>
                        <?php if($this->canbetranslate){?>
                            <td class="right">
                                <?php foreach($this->langs as $lang) { ?>
                                    <a href="<?=$this->baseUrl();?>/admin/inwestycje-dziennik/tlumaczenie/id/<?=$this->escape($pozycja->id);?>/lang/<?=$this->escape($lang->kod);?>/inwest/<?=$this->inwestycja->id;?>/" class="actionBtn tip" title="Edytuj tłumaczenie: <?=$this->escape($lang->nazwa);?>"><img src="<?=$this->baseUrl();?>/public/gfx/flags/<?=$this->escape($lang->flaga);?>"></a>
                                <?php } ?>
                            </td>
                        <?php } ?>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
            <div class="table-footer">
                <a href="<?=$this->baseUrl();?>/admin/inwestycje-dziennik/add/id/<?=$this->inwestycja->id;?>/" class="button greyishBtn">Dodaj wpis</a>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" language="javascript">
    //<![CDATA[
    $(document).ready(function(){
        $(".content").sortuj('<?=$this->baseUrl();?>/admin/inwestycje/ustaw/co/inwestycje_news/');
    });
    //]]>
</script>