<div class="container page-menu page-<?=$this->page->tag;?>">
    <div class="row">
        <div class="col-12 text-justify">
            <?=parse($this->page->tekst); ?>
        </div>
    </div>
</div>
<?php if($this->listamieszkan) {?>
    <?= $this->partial('inwestycje/partials/list-list.phtml', array(
        'powierzchnia' => $this->powierzchnia,
        'inwestycja' => $this->inwestycja
    ));?>
<?php } ?>

