<div id="slider"></div>

<div id="mainAbout">
    <div class="container">
        <div class="row inline">
            <div class="col-12 col-lg-6">
                <div class="section-img">
                    <img src="<?=$this->filesUrl(); ?>/inline/0726101052-wizualizacja-inwestycji-apartamenty-sucharskiego.jpg" alt="<?=$this->getInline($this->inline, 1, 'obrazek_alt');?>" data-img="1" class="d-none d-xl-block" width="740" height="660">
                    <img src="<?=$this->filesUrl(); ?>/inline/0726101052-wizualizacja-inwestycji-apartamenty-sucharskiego-1530.jpg" alt="<?=$this->getInline($this->inline, 1, 'obrazek_alt');?>" data-img="1" class="d-none d-lg-block d-xl-none" width="450" height="700">
                    <img src="<?=$this->filesUrl(); ?>/inline/0726101052-wizualizacja-inwestycji-apartamenty-sucharskiego-991.jpg" alt="<?=$this->getInline($this->inline, 1, 'obrazek_alt');?>" data-img="1" class="d-block d-lg-none" width="690" height="576">
                </div>
            </div>
            <div class="col-12 col-lg-6 d-flex align-items-center">
                <div class="section-text pl-0 pl-lg-5 pt-4 pt-lg-0">
                    <h2 class="section-title" data-modaltytul="1"><?=$this->getInline($this->inline, 1, 'modaltytul');?></h2>
                    <div data-modaleditortext="1">
                        <?=$this->getInline($this->inline, 1, 'modaleditortext');?>
                    </div>
                </div>
            </div>
            <?=$this->inlineModal(1, 'modaltytul,modaleditortext', '740,660');?>
            <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
        </div>
    </div>
</div>

<div id="mainBox">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-6 col-sm-4 col-lg">
                <div class="box-icon">
                    <img src="<?=$this->gfxUrl();?>/room-icon.png" alt="Ikonka planu mieszkania" height="65" width="65">
                    <strong>20</strong>
                    <span>mieszkań</span>
                </div>
            </div>
            <div class="col-6 col-sm-4 col-lg">
                <div class="box-icon">
                    <img src="<?=$this->gfxUrl();?>/floor-icon.png" alt="Ikonka piętra" height="65" width="65">
                    <strong>4</strong>
                    <span>kondygnacje</span>
                </div>
            </div>
            <div class="col-6 col-sm-4 col-lg">
                <div class="box-icon">
                    <img src="<?=$this->gfxUrl();?>/parking-icon.png" alt="Ikonka miejsca parkingowego" height="65" width="65">
                    <strong>19</strong>
                    <span>miejsc <br>parkingowych</span>
                </div>
            </div>
            <div class="col-6 col-sm-4 col-lg">
                <div class="box-icon">
                    <img src="<?=$this->gfxUrl();?>/garden-icon.png" alt="Ikonka ogródka" height="65" width="65">
                    <strong>5</strong>
                    <span>mieszkań <br>z ogródkami</span>
                </div>
            </div>
            <div class="col col-sm-4 col-lg">
                <div class="box-icon">
                    <img src="<?=$this->gfxUrl();?>/park-icon.png" alt="Ikonka ogródka" height="65" width="65">
                    <strong>1,5km</strong>
                    <span>Bolimowski Park Krajobrazowy</span>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="mainRooms">
    <div class="container">
        <div class="row d-flex justify-content-center text-center inline">
            <div class="col-12">
                <h2 class="section-title" data-modaltytul="2"><?=$this->getInline($this->inline, 2, 'modaltytul');?></h2>
            </div>
            <div class="col-12 col-xl-6">
                <p class="section-title-text" data-modaleditor="2"><?=$this->getInline($this->inline, 2, 'modaleditor');?></p>
            </div>
            <?=$this->inlineModal(2, 'modaltytul,modaleditor', '740,660');?>
            <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
        </div>
        <div class="row">
            <div class="col-12">
                <ul class="nav nav-tabs mt-5" id="roomsTab" role="tablist">
                    <?php foreach($this->showrooms as $int => $showroom) { ?>
                    <li class="nav-item" role="presentation">
                        <a class="nav-link<?php if($int == 0){?> active<?php } ?>" id="room<?=$showroom->id;?>-tab" data-toggle="tab" href="#room<?=$showroom->id;?>" role="tab" aria-controls="room<?=$showroom->id;?>"<?php if($int == 0){?>  aria-selected="true"<?php } ?>><?=$showroom->name;?></a>
                    </li>
                    <?php } ?>
                </ul>
                <div class="tab-content" id="roomsTabContent">
                    <?php foreach($this->showrooms as $int => $showroom) { ?>
                    <div class="tab-pane fade <?php if($int == 0){?>show active<?php } ?>" id="room<?=$showroom->id;?>" role="tabpanel" aria-labelledby="room<?=$showroom->id;?>-tab">
                        <div class="row">
                            <div class="order-2 order-lg-1 col-12 col-lg-4 col-xl-3">
                                <div class="room-text">
                                    <h3><?=$showroom->area;?></h3>
                                    <p><?=$showroom->text;?></p>
                                    <?=$showroom->params;?>
                                    <a class="bttn bttn-green d-none" href="#">POKAŻ MIESZKANIA</a>
                                </div>
                            </div>
                            <div class="order-1 order-lg-2 col-12 col-lg-8 col-xl-9 d-flex align-items-center justify-content-center">
                                <div class="room-img">
                                    <img src="<?=$this->filesUrl();?>/showrooms/<?=$this->escape($showroom->file);?>" alt="<?=$showroom->name;?>" width="900" height="660">
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="mainPlan">
    <div class="container">
        <div class="row d-flex justify-content-center text-center mb-3">
            <div class="col-12">
                <h2 class="section-title">MIESZKANIA</h2>
            </div>
            <div class="col-12 col-xl-6">
                <p class="section-title-text">Z planu budynku wybierz pietro, lub wybierz mieszkanie z <a href="#roomTable" class="scrollto" data-offset="103"><b>listy</b> <i class="las la-angle-double-down"></i></a></p>
            </div>
        </div>
        <div class="row" id="plans">
            <div class="col-12">
                <div class="position-relative">
                    <div id="planImg">
                        <img src="<?=$this->filesUrl(); ?>/inwestycje/plan/<?=$this->plan->plik;?>" alt="Plan inwestycji" style="max-width:100%;height:auto;" id="buildingmap" usemap="#buildingmap">
                        <map name="buildingmap">
                            <?php foreach($this->floors as $int => $f) {
                                if($this->pietro_stats)
                                {
                                    $floor_stats = '';
                                    $status = ['1', '2', '3'];
                                    foreach($status as $s) {
                                        $floor_stats .= "<p class='floor-stats'>".$this->roomStatus($s).": <span>".substr_count($this->pietro_stats[$f->id], $s)."</span></p>";
                                    }
                                } else {
                                    $floor_stats = '';
                                }

                                $floor =  str_replace('href=""','href="#"', $f->html);
                                $floor =  str_replace('shape="polygon"','shape="poly"', $floor);
                                echo str_replace('alt=""','title="<h6>'.$f->nazwa.'</h6>" alt="pietro-'.$f->id.'" data-floornumber="'.$f->id.'" data-slickorder="'.($int + 1).'" data-floortype="'.$f->typ.'"', $floor);
                            } ?>
                        </map>
                    </div>
                </div>
            </div>

            <?php foreach($this->floors as $f) { ?>
                <div class="col-12">
                    <div id="planImg">
                        <img src="<?=$this->filesUrl(); ?>/inwestycje/pietro/<?=$f->plik;?>" alt="<?=$f->nazwa;?>" style="max-width:100%;height:auto;" id="floormap-<?=$f->id;?>" class="floormap" usemap="#floormap-<?=$f->id;?>">
                    </div>
                    <map name="floormap-<?=$f->id;?>">
                        <?php foreach($this->domki as $mieszkania) {
                            if($f->id == $mieszkania->id_pietro) {
                                if($mieszkania->status <> 2) {
                                    $mieszkanie = str_replace('href=""', 'href="' . $this->url(array(
                                            'numer' => $mieszkania->id
                                        ), 'inwestycja-domek') . '" data-id="' . $mieszkania->id . '"', $mieszkania->html);
                                } else {
                                    $mieszkanie = str_replace('href=""','href="#"', $mieszkania->html);
                                }

                                $mieszkanie =  str_replace('shape="polygon"','shape="poly"', $mieszkanie);
                                $mieszkanie = str_replace('alt=""','id="'.$mieszkania->id.'" alt="dom-'.$mieszkania->id.'" title="<b>'.$mieszkania->nazwa.'</b><br />Powierzchnia: <b class=fr>'.$mieszkania->metry.' m<sup>2</sup></b><br />Pokoje: <b class=fr>'.$mieszkania->pokoje.'</b><br />'.$this->roomStatus($mieszkania->status).'" data-color="plan-status-'.$mieszkania->status.'" class="inline plan-status-'.$mieszkania->status.'"', $mieszkanie);
                                echo $mieszkanie;
                            }
                        } ?>
                    </map>
                </div>
            <?php } ?>
        </div>
        <div class="row plan-nav">
            <div class="col">
                <a href="#" class="bttn bttn-active" data-floornumber="0">Budynek</a>
            </div>
            <?php foreach($this->floors as $int => $f) { ?>
                <div class="col-3 col-sm">
                    <a href="#" class="bttn" data-floor="<?=$f->id;?>" data-floornumber="<?=$int + 1;?>"><?=$f->nazwa;?></a>
                </div>
            <?php } ?>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-12">
                <table class="table" id="roomTable">
                    <thead>
                    <tr>
                        <th class="nosort">Lokal</th>
                        <th class="sort">Piętro</th>
                        <th class="sort">Powierzchnia m<sup>2</sup></th>
                        <th class="nosort">Dostępność</th>
                        <th class="nosort">Plan</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach($this->domki as $d) { ?>
                        <tr data-floor="<?=$d->id_pietro;?>" data-home="<?=$d->numer;?>">
                            <td><?=$d->nazwa;?></td>
                            <td><?=$d->numer_pietro - 1;?></td>
                            <td><?=str_replace('.', '.', $d->metry);?></td>
                            <td><span class="<?=$this->roomStatusTag($d->status);?>-ap"><?=$this->roomStatus($d->status);?></span></td>
                            <td><a href="<?= $this->url(array('numer' => $d->id), 'inwestycja-domek');?>" class="bttn bttn-green">Zobacz plan</a></td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div id="mainLocation">
    <div class="container">
        <div class="row d-flex justify-content-center text-center inline">
            <div class="col-12">
                <h2 class="section-title" data-modaltytul="3"><?=$this->getInline($this->inline, 3, 'modaltytul');?></h2>
            </div>
            <div class="col-12 col-xl-6">
                <p class="section-title-text" data-modaleditor="3"><?=$this->getInline($this->inline, 3, 'modaleditor');?></p>
            </div>
            <?=$this->inlineModal(3, 'modaltytul,modaleditor', '740,660');?>
            <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
        </div>
        <div class="row">
            <div class="col-12 mt-3 mt-sm-5 mb-3 mb-sm-5">
                <div id="mapHolder"></div>
            </div>
        </div>
        <div class="row location-carousel d-none">
            <div class="col-3">
                <div class="location-box">
                    <img src="<?=$this->gfxUrl();?>/market.jpg" alt="<?= $this->header['nazwa']; ?>" width="355" height="460">
                    <div class="location-box-shadow">
                        <div class="location-box-info">
                            <h3>Market spożywczy</h3>
                            <p>bezpośrednio obok</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-3">
                <div class="location-box">
                    <img src="<?=$this->gfxUrl();?>/market.jpg" alt="<?= $this->header['nazwa']; ?>" width="355" height="460">
                    <div class="location-box-shadow">
                        <div class="location-box-info">
                            <h3>Market spożywczy</h3>
                            <p>bezpośrednio obok</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-3">
                <div class="location-box">
                    <img src="<?=$this->gfxUrl();?>/market.jpg" alt="<?= $this->header['nazwa']; ?>" width="355" height="460">
                    <div class="location-box-shadow">
                        <div class="location-box-info">
                            <h3>Market spożywczy</h3>
                            <p>bezpośrednio obok</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-3">
                <div class="location-box">
                    <img src="<?=$this->gfxUrl();?>/market.jpg" alt="<?= $this->header['nazwa']; ?>" width="355" height="460">
                    <div class="location-box-shadow">
                        <div class="location-box-info">
                            <h3>Market spożywczy</h3>
                            <p>bezpośrednio obok</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row d-flex justify-content-center">
            <?php foreach($this->atuty as $a) {?>
            <div class="col-6 col-md-4 col-lg-3 pl-3 pl-sm-4 pl-xl-5">
                <div class="location-box-small">
                    <div class="location-box-icon"><i class="las la-map-marker"></i></div>
                    <h3><?=$a->name;?></h3>
                    <p><?=$a->distance;?></p>
                </div>
            </div>
            <?php } ?>
        </div>
    </div>
</div>

<div id="mainGallery">
    <div class="container">
        <div class="row d-flex justify-content-center text-center inline">
            <div class="col-12">
                <h2 class="section-title" data-modaltytul="4"><?=$this->getInline($this->inline, 4, 'modaltytul');?></h2>
            </div>
            <div class="col-12 col-xl-6">
                <p class="section-title-text" data-modaleditor="4"><?=$this->getInline($this->inline, 4, 'modaleditor');?></p>
            </div>
            <?=$this->inlineModal(4, 'modaltytul,modaleditor', '740,660');?>
            <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
        </div>
    </div>
    <div class="container-fluid mt-4 mt-sm-5">
        <div class="row gallery-carousel">
            <div class="col-10">
                <img src="<?=$this->filesUrl(); ?>/galeria/1.jpg" width="1270" height="760" alt="">
                <div class="gallery-apla d-none"><p>Curabitur eget odio in neque tincidunt luctus. Cras ultricies sed libero ut rutrum. Phasellus accumsan mi neque, vestibulum fringilla tortor consequat pharetra.</p></div>
            </div>
            <div class="col-10">
                <img src="<?=$this->filesUrl(); ?>/galeria/2.jpg" width="1270" height="760" alt="">
                <div class="gallery-apla d-none"><p>Curabitur eget odio in neque tincidunt luctus. Cras ultricies sed libero ut rutrum. Phasellus accumsan mi neque, vestibulum fringilla tortor consequat pharetra.</p></div>
            </div>
            <div class="col-10">
                <img src="<?=$this->filesUrl(); ?>/galeria/3.jpg" width="1270" height="760" alt="">
                <div class="gallery-apla d-none"><p>Curabitur eget odio in neque tincidunt luctus. Cras ultricies sed libero ut rutrum. Phasellus accumsan mi neque, vestibulum fringilla tortor consequat pharetra.</p></div>
            </div>
            <div class="col-10">
                <img src="<?=$this->filesUrl(); ?>/galeria/4.jpg" width="1270" height="760" alt="">
                <div class="gallery-apla d-none"><p>Curabitur eget odio in neque tincidunt luctus. Cras ultricies sed libero ut rutrum. Phasellus accumsan mi neque, vestibulum fringilla tortor consequat pharetra.</p></div>
            </div>
            <div class="col-10">
                <img src="<?=$this->filesUrl(); ?>/galeria/5.jpg" width="1270" height="760" alt="">
                <div class="gallery-apla d-none"><p>Curabitur eget odio in neque tincidunt luctus. Cras ultricies sed libero ut rutrum. Phasellus accumsan mi neque, vestibulum fringilla tortor consequat pharetra.</p></div>
            </div>
        </div>
    </div>
</div>

<div id="mainWhy">
    <div class="container">
        <div class="row d-flex justify-content-center text-center inline">
            <div class="col-12">
                <h2 class="section-title" data-modaltytul="5"><?=$this->getInline($this->inline, 5, 'modaltytul');?></h2>
            </div>
            <div class="col-12 col-xl-6">
                <p class="section-title-text" data-modaleditor="5"><?=$this->getInline($this->inline, 5, 'modaleditor');?></p>
            </div>
            <?=$this->inlineModal(5, 'modaltytul,modaleditor', '740,660');?>
            <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
        </div>
        <div class="row mt-3 mt-xl-0">
            <div class="col-12 d-flex flex-wrap justify-content-center">
                <div class="why-box-col">
                    <div class="why-box">
                        <div class="why-box-img">
                            <img src="<?=$this->gfxUrl();?>/parking-podziemny-icon.png" alt="Ikonka parkingu podziemnego" height="72" width="72">
                        </div>
                        <div class="why-box-text">
                            Garaż podziemny
                        </div>
                    </div>
                </div>
                <div class="why-box-col">
                    <div class="why-box">
                        <div class="why-box-img">
                            <img src="<?=$this->gfxUrl();?>/ladowarka.png" alt="Ikonka filtru antysmogowego" height="72" width="72">
                        </div>
                        <div class="why-box-text">
                            Stacja ładowania pojazdów elektrycznych
                        </div>
                    </div>
                </div>
                <div class="why-box-col">
                    <div class="why-box">
                        <div class="why-box-img">
                            <img src="<?=$this->gfxUrl();?>/winda-icon.png" alt="Ikonka windy" height="72" width="72">
                        </div>
                        <div class="why-box-text">
                            Winda
                        </div>
                    </div>
                </div>
                <div class="why-box-col">
                    <div class="why-box">
                        <div class="why-box-img">
                            <img src="<?=$this->gfxUrl();?>/led-icon.png" alt="Ikonka oświetlenia LED" height="72" width="72">
                        </div>
                        <div class="why-box-text">
                            Oświetlenie LED w korytarzach
                        </div>
                    </div>
                </div>
                <div class="why-box-col">
                    <div class="why-box">
                        <div class="why-box-img">
                            <img src="<?=$this->gfxUrl();?>/filtr-icon.png" alt="Ikonka filtru antysmogowego" height="72" width="72">
                        </div>
                        <div class="why-box-text">
                            Filtry antysmogowe
                        </div>
                    </div>
                </div>
                <div class="why-box-col">
                    <div class="why-box">
                        <div class="why-box-img">
                            <img src="<?=$this->gfxUrl();?>/garden-flower-icon.png" alt="Ikonka ogrodu" height="72" width="72">
                        </div>
                        <div class="why-box-text">
                            5 mieszkań z dużymi ogródkami
                        </div>
                    </div>
                </div>
                <div class="why-box-col">
                    <div class="why-box">
                        <div class="why-box-img">
                            <img src="<?=$this->gfxUrl();?>/wideodomofon.png" alt="Ikonka wideodomofonu" height="72" width="72">
                        </div>
                        <div class="why-box-text">
                            Videodomofony
                        </div>
                    </div>
                </div>
                <div class="why-box-col">
                    <div class="why-box">
                        <div class="why-box-img">
                            <img src="<?=$this->gfxUrl();?>/monitoring-icon.png" alt="Ikonka kamery monitoringu" height="72" width="72">
                        </div>
                        <div class="why-box-text">
                            Monitoring CCTV
                        </div>
                    </div>
                </div>
                <div class="why-box-col">
                    <div class="why-box">
                        <div class="why-box-img">
                            <img src="<?=$this->gfxUrl();?>/rowerownia-icon.png" alt="Ikonka rowerowni" height="72" width="72">
                        </div>
                        <div class="why-box-text">
                            Rowerownia
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="mainInvestor">
    <div class="container">
        <div class="row inline">
            <div class="col-12 col-xl-5 d-flex align-items-center">
                <div class="section-img">
                    <img src="<?=$this->getInline($this->inline, 6, 'obrazek');?>" alt="<?=$this->getInline($this->inline, 6, 'obrazek_alt');?>" data-img="6" width="610" height="450">
                </div>
            </div>
            <div class="col-12 col-xl-7 d-flex align-items-center">
                <div class="section-text pl-0 pl-xl-5">
                    <h2 class="section-title" data-modaltytul="6"><?=$this->getInline($this->inline, 6, 'modaltytul');?></h2>
                    <div data-modaleditortext="6">
                        <?=$this->getInline($this->inline, 6, 'modaleditortext');?>
                    </div>
                </div>
            </div>
            <?=$this->inlineModal(6, 'modaltytul,modaleditortext,obrazek,obrazek_alt', '610,450');?>
            <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
        </div>
    </div>
</div>

<div id="mainContact">
    <div class="container pb-5">
        <div class="row d-flex justify-content-center text-center inline">
            <div class="col-12">
                <h2>KONTAKT</h2>
            </div>
            <div class="col-12 col-xl-6">
                <p class="section-title-text text-center">
                    <b>EPS Development Sp. z o.o.</b><br>
                    Kozietulskiego 14<br>
                    960199 Skierniewice<br>
                    <br>
                    NIP: 836-187-69-01<br>
                    REGON: 389216974<br>
                    KRS: 0000905123<br>
                    <br>
                    <a href="mailto:sprzedaz@epsdevelopment.pl">sprzedaz@epsdevelopment.pl</a>
                </p>
            </div>
        </div>
    </div>
</div>