<div id="slider"></div>

<div id="mainAbout">
    <div class="container">
        <div class="row inline">
            <div class="col-6">
                <div class="section-img">
                    <img src="<?=$this->getInline($this->inline, 1, 'obrazek');?>" alt="<?=$this->getInline($this->inline, 1, 'obrazek_alt');?>" data-img="1" width="740" height="660">
                </div>
            </div>
            <div class="col-6 d-flex align-items-center">
                <div class="section-text pl-5">
                    <h2 class="section-title" data-modaltytul="1"><?=$this->getInline($this->inline, 1, 'modaltytul');?></h2>
                    <div data-modaleditortext="1">
                        <?=$this->getInline($this->inline, 1, 'modaleditortext');?>
                    </div>
                </div>
            </div>
            <?=$this->inlineModal(1, 'modaltytul,modaleditortext,obrazek,obrazek_alt', '740,660');?>
            <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
        </div>
    </div>
</div>

<div id="mainBox">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="box-icon">
                    <img src="https://placehold.co/65x65" alt="">
                    <strong>20</strong>
                    <span>mieszkań</span>
                </div>
            </div>
            <div class="col">
                <div class="box-icon">
                    <img src="https://placehold.co/65x65" alt="">
                    <strong>4</strong>
                    <span>kondygnacje</span>
                </div>
            </div>
            <div class="col">
                <div class="box-icon">
                    <img src="https://placehold.co/65x65" alt="">
                    <strong>19</strong>
                    <span>miejsc <br>parkingowych</span>
                </div>
            </div>
            <div class="col">
                <div class="box-icon">
                    <img src="https://placehold.co/65x65" alt="">
                    <strong>5</strong>
                    <span>mieszkań <br>z ogródkami</span>
                </div>
            </div>
            <div class="col">
                <div class="box-icon">
                    <img src="https://placehold.co/65x65" alt="">
                    <strong>1,5km</strong>
                    <span>Bolimowski Park Krajobrazowy</span>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="mainRooms">
    <div class="container">
        <div class="row d-flex justify-content-center text-center inline">
            <div class="col-12">
                <h2 class="section-title" data-modaltytul="2"><?=$this->getInline($this->inline, 2, 'modaltytul');?></h2>
            </div>
            <div class="col-6">
                <p class="section-title-text" data-modaleditor="2"><?=$this->getInline($this->inline, 2, 'modaleditor');?></p>
            </div>
            <?=$this->inlineModal(2, 'modaltytul,modaleditor', '740,660');?>
            <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
        </div>
        <div class="row">
            <div class="col-12">
                <ul class="nav nav-tabs mt-5" id="roomsTab" role="tablist">
                    <li class="nav-item" role="presentation">
                        <a class="nav-link active" id="room1-tab" data-toggle="tab" href="#room1" role="tab" aria-controls="room1" aria-selected="true">MIESZKANIE 1</a>
                    </li>
                    <li class="nav-item" role="presentation">
                        <a class="nav-link" id="room2-tab" data-toggle="tab" href="#room2" role="tab" aria-controls="room2" aria-selected="false">MIESZKANIE 2</a>
                    </li>
                    <li class="nav-item" role="presentation">
                        <a class="nav-link" id="room3-tab" data-toggle="tab" href="#room3" role="tab" aria-controls="room3" aria-selected="false">MIESZKANIE 3</a>
                    </li>
                    <li class="nav-item" role="presentation">
                        <a class="nav-link" id="room4-tab" data-toggle="tab" href="#room4" role="tab" aria-controls="room4" aria-selected="false">MIESZKANIE 4</a>
                    </li>
                    <li class="nav-item" role="presentation">
                        <a class="nav-link" id="room5-tab" data-toggle="tab" href="#room5" role="tab" aria-controls="room5" aria-selected="false">MIESZKANIE 5</a>
                    </li>
                    <li class="nav-item" role="presentation">
                        <a class="nav-link" id="room6-tab" data-toggle="tab" href="#room6" role="tab" aria-controls="room6" aria-selected="false">MIESZKANIE 6</a>
                    </li>
                </ul>
                <div class="tab-content" id="roomsTabContent">
                    <div class="tab-pane fade show active" id="room1" role="tabpanel" aria-labelledby="room1-tab">
                        <div class="row">
                            <div class="col-3">
                                <div class="room-text">
                                    <h3>52.4 m<sup>2</sup></h3>
                                    <p>Donec faucibus est in tortor lacinia, ut rhoncus quam tempor. Etiam tincidunt tellus faucibus dui mattis vulputate in nec risus. Nulla facilisi. Phasellus mi est, laoreet eu vestibulum at, feugiat ut nisl.</p>
                                    <ul class="mb-0 list-unstyled">
                                        <li>Pokoje<span>2</span></li>
                                        <li>Sypialnia<span>1</span></li>
                                        <li>Balkon<span>12 m<sup>2</sup></span></li>
                                        <li>Łazienka<span>7 m<sup>2</sup></span></li>
                                    </ul>
                                    <a class="bttn bttn-green" href="#">POKAŻ MIESZKANIA</a>
                                </div>
                            </div>
                            <div class="col-9 d-flex align-items-center justify-content-center">
                                <div class="room-img">
                                    <img src="<?=$this->gfxUrl();?>/przykladowe.jpg" alt="<?= $this->header['nazwa']; ?>" width="900" height="666">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="room2" role="tabpanel" aria-labelledby="room2-tab">
                        <div class="row">
                            <div class="col-3">
                                <div class="room-text">
                                    <h3>52.4 m<sup>2</sup></h3>
                                    <p>Donec faucibus est in tortor lacinia, ut rhoncus quam tempor. Etiam tincidunt tellus faucibus dui mattis vulputate in nec risus. Nulla facilisi. Phasellus mi est, laoreet eu vestibulum at, feugiat ut nisl.</p>
                                    <ul class="mb-0 list-unstyled">
                                        <li>Pokoje<span>2</span></li>
                                        <li>Sypialnia<span>1</span></li>
                                        <li>Balkon<span>12 m<sup>2</sup></span></li>
                                        <li>Łazienka<span>7 m<sup>2</sup></span></li>
                                    </ul>
                                    <a class="bttn bttn-green" href="#">POKAŻ MIESZKANIA</a>
                                </div>
                            </div>
                            <div class="col-9 d-flex align-items-center justify-content-center">
                                <div class="room-img">
                                    <img src="<?=$this->gfxUrl();?>/przykladowe.jpg" alt="<?= $this->header['nazwa']; ?>" width="900" height="666">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="room3" role="tabpanel" aria-labelledby="room3-tab">
                        <div class="row">
                            <div class="col-3">
                                <div class="room-text">
                                    <h3>74.8 m<sup>2</sup></h3>
                                    <p>Donec faucibus est in tortor lacinia, ut rhoncus quam tempor. Etiam tincidunt tellus faucibus dui mattis vulputate in nec risus. Nulla facilisi. Phasellus mi est, laoreet eu vestibulum at, feugiat ut nisl.</p>
                                    <ul class="mb-0 list-unstyled">
                                        <li>Pokoje<span>2</span></li>
                                        <li>Sypialnia<span>1</span></li>
                                        <li>Balkon<span>12 m<sup>2</sup></span></li>
                                        <li>Łazienka<span>7 m<sup>2</sup></span></li>
                                    </ul>
                                    <a class="bttn bttn-green" href="#">POKAŻ MIESZKANIA</a>
                                </div>
                            </div>
                            <div class="col-9 d-flex align-items-center justify-content-center">
                                <div class="room-img">
                                    <img src="<?=$this->gfxUrl();?>/przykladowe.jpg" alt="<?= $this->header['nazwa']; ?>" width="900" height="666">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="room4" role="tabpanel" aria-labelledby="room3-tab">
                        <div class="row">
                            <div class="col-3">
                                <div class="room-text">
                                    <h3>80.56 m<sup>2</sup></h3>
                                    <p>Donec faucibus est in tortor lacinia, ut rhoncus quam tempor. Etiam tincidunt tellus faucibus dui mattis vulputate in nec risus. Nulla facilisi. Phasellus mi est, laoreet eu vestibulum at, feugiat ut nisl.</p>
                                    <ul class="mb-0 list-unstyled">
                                        <li>Pokoje<span>2</span></li>
                                        <li>Sypialnia<span>1</span></li>
                                        <li>Balkon<span>12 m<sup>2</sup></span></li>
                                        <li>Łazienka<span>7 m<sup>2</sup></span></li>
                                    </ul>
                                    <a class="bttn bttn-green" href="#">POKAŻ MIESZKANIA</a>
                                </div>
                            </div>
                            <div class="col-9 d-flex align-items-center justify-content-center">
                                <div class="room-img">
                                    <img src="<?=$this->gfxUrl();?>/przykladowe.jpg" alt="<?= $this->header['nazwa']; ?>" width="900" height="666">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="room5" role="tabpanel" aria-labelledby="room3-tab">
                        <div class="row">
                            <div class="col-3">
                                <div class="room-text">
                                    <h3>97.5 m<sup>2</sup></h3>
                                    <p>Donec faucibus est in tortor lacinia, ut rhoncus quam tempor. Etiam tincidunt tellus faucibus dui mattis vulputate in nec risus. Nulla facilisi. Phasellus mi est, laoreet eu vestibulum at, feugiat ut nisl.</p>
                                    <ul class="mb-0 list-unstyled">
                                        <li>Pokoje<span>2</span></li>
                                        <li>Sypialnia<span>1</span></li>
                                        <li>Balkon<span>12 m<sup>2</sup></span></li>
                                        <li>Łazienka<span>7 m<sup>2</sup></span></li>
                                    </ul>
                                    <a class="bttn bttn-green" href="#">POKAŻ MIESZKANIA</a>
                                </div>
                            </div>
                            <div class="col-9 d-flex align-items-center justify-content-center">
                                <div class="room-img">
                                    <img src="<?=$this->gfxUrl();?>/przykladowe.jpg" alt="<?= $this->header['nazwa']; ?>" width="900" height="666">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="room6" role="tabpanel" aria-labelledby="room3-tab">
                        <div class="row">
                            <div class="col-3">
                                <div class="room-text">
                                    <h3>102.4 m<sup>2</sup></h3>
                                    <p>Donec faucibus est in tortor lacinia, ut rhoncus quam tempor. Etiam tincidunt tellus faucibus dui mattis vulputate in nec risus. Nulla facilisi. Phasellus mi est, laoreet eu vestibulum at, feugiat ut nisl.</p>
                                    <ul class="mb-0 list-unstyled">
                                        <li>Pokoje<span>2</span></li>
                                        <li>Sypialnia<span>1</span></li>
                                        <li>Balkon<span>12 m<sup>2</sup></span></li>
                                        <li>Łazienka<span>7 m<sup>2</sup></span></li>
                                    </ul>
                                    <a class="bttn bttn-green" href="#">POKAŻ MIESZKANIA</a>
                                </div>
                            </div>
                            <div class="col-9 d-flex align-items-center justify-content-center">
                                <div class="room-img">
                                    <img src="<?=$this->gfxUrl();?>/przykladowe.jpg" alt="<?= $this->header['nazwa']; ?>" width="900" height="666">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

<div id="mainPlan">
    <div class="container">
        <div class="row d-flex justify-content-center text-center">
            <div class="col-12">
                <h2 class="section-title">MIESZKANIA</h2>
            </div>
            <div class="col-6">
                <p class="section-title-text">Z planu budynku wybierz pietro, lub wybierz mieszkanie z <a href="#" class="scrollto"><b>listy</b> <i class="las la-angle-double-down"></i></a></p>
            </div>
        </div>
        <div class="row" id="plans">
            <div class="col-12">
                <div class="position-relative">
                    <div id="planImg">
                        <img src="<?=$this->filesUrl(); ?>/inwestycje/plan/<?=$this->plan->plik;?>" alt="Plan inwestycji" style="max-width:100%;height:auto;" id="buildingmap" usemap="#buildingmap">
                        <map name="buildingmap">
                            <?php foreach($this->floors as $f) {
                                if($this->pietro_stats)
                                {
                                    $floor_stats = '';
                                    $status = ['1', '2', '3'];
                                    foreach($status as $s) {
                                        $floor_stats .= "<p class='floor-stats'>".$this->roomStatus($s).": <span>".substr_count($this->pietro_stats[$f->id], $s)."</span></p>";
                                    }
                                } else {
                                    $floor_stats = '';
                                }

                                $floor =  str_replace('href=""','href="#"', $f->html);
                                $floor =  str_replace('shape="polygon"','shape="poly"', $floor);
                                echo str_replace('alt=""','title="<h6>'.$f->nazwa.'</h6>" alt="pietro-'.$f->id.'" data-floornumber="'.$f->numer.'" data-floortype="'.$f->typ.'"', $floor);
                            } ?>
                        </map>
                    </div>
                </div>
            </div>

            <?php foreach($this->floors as $f) { ?>
                <div class="col-12">
                    <div id="planImg">
                        <img src="<?=$this->filesUrl(); ?>/inwestycje/pietro/<?=$f->plik;?>" alt="<?=$f->nazwa;?>" style="max-width:100%;height:auto;" id="floormap-<?=$f->id;?>" class="floormap" usemap="#floormap-<?=$f->id;?>">
                    </div>
                    <map name="floormap-<?=$f->id;?>">
                        <?php foreach($this->domki as $mieszkania) {
                            if($f->id == $mieszkania->id_pietro) {
                                if($mieszkania->status <> 2) {
                                    $mieszkanie = str_replace('href=""', 'href="' . $this->url(array(
                                            'numer' => $mieszkania->numer
                                        ), 'inwestycja-domek') . '" data-id="' . $mieszkania->id . '"', $mieszkania->html);
                                } else {
                                    $mieszkanie = str_replace('href=""','href="#"', $mieszkania->html);
                                }

                                $mieszkanie =  str_replace('shape="polygon"','shape="poly"', $mieszkanie);
                                $mieszkanie = str_replace('alt=""','id="'.$mieszkania->id.'" alt="dom-'.$mieszkania->id.'" title="<b>'.$mieszkania->nazwa.'</b><br />Powierzchnia: <b class=fr>'.$mieszkania->metry.' m<sup>2</sup></b><br />Pokoje: <b class=fr>'.$mieszkania->pokoje.'</b><br />'.$this->roomStatus($mieszkania->status).'" data-color="plan-status-'.$mieszkania->status.'" class="inline plan-status-'.$mieszkania->status.'"', $mieszkanie);
                                echo $mieszkanie;
                            }
                        } ?>
                    </map>
                </div>
            <?php } ?>
        </div>
        <div class="row plan-nav">
            <div class="col">
                <a href="#" class="bttn bttn-active" data-floornumber="0">Budynek</a>
            </div>
            <?php foreach($this->floors as $f) { ?>
                <div class="col-3 col-sm">
                    <a href="#" class="bttn" data-floornumber="<?=$f->numer_lista;?>"><?=$f->nazwa;?></a>
                </div>
            <?php } ?>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-12">
                <table class="table">
                    <thead>
                    <tr>
                        <th class="nosort">Lokal</th>
                        <th class="sort">Piętro</th>
                        <th class="sort">Powierzchnia m<sup>2</sup></th>
                        <th class="nosort">Dostępność</th>
                        <th class="nosort">Plan</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach($this->domki as $d) { ?>
                        <tr data-floor="<?=$d->numer_pietro + 1;?>">
                            <td><?=$d->nazwa;?></td>
                            <td><?=$d->numer_pietro;?></td>
                            <td><?=str_replace('.', '.', $d->metry);?></td>
                            <td><span class="<?=$this->roomStatusTag($d->status);?>-ap"><?=$this->roomStatus($d->status);?></span></td>
                            <td><a href="<?= $this->url(array('numer' => $d->numer), 'inwestycja-domek');?>" class="bttn bttn-green">Zobacz plan</a></td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div id="mainLocation">
    <div class="container">
        <div class="row d-flex justify-content-center text-center inline">
            <div class="col-12">
                <h2 class="section-title" data-modaltytul="3"><?=$this->getInline($this->inline, 3, 'modaltytul');?></h2>
            </div>
            <div class="col-6">
                <p class="section-title-text" data-modaleditor="3"><?=$this->getInline($this->inline, 3, 'modaleditor');?></p>
            </div>
            <?=$this->inlineModal(3, 'modaltytul,modaleditor', '740,660');?>
            <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
        </div>
        <div class="row">
            <div class="col-12 mt-5 mb-5">
                <div id="mapHolder"></div>
            </div>
        </div>
        <div class="row location-carousel">
            <div class="col-3">
                <div class="location-box">
                    <img src="<?=$this->gfxUrl();?>/market.jpg" alt="<?= $this->header['nazwa']; ?>" width="355" height="460">
                    <div class="location-box-shadow">
                        <div class="location-box-info">
                            <h3>Market spożywczy</h3>
                            <p>bezpośrednio obok</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-3">
                <div class="location-box">
                    <img src="<?=$this->gfxUrl();?>/market.jpg" alt="<?= $this->header['nazwa']; ?>" width="355" height="460">
                    <div class="location-box-shadow">
                        <div class="location-box-info">
                            <h3>Market spożywczy</h3>
                            <p>bezpośrednio obok</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-3">
                <div class="location-box">
                    <img src="<?=$this->gfxUrl();?>/market.jpg" alt="<?= $this->header['nazwa']; ?>" width="355" height="460">
                    <div class="location-box-shadow">
                        <div class="location-box-info">
                            <h3>Market spożywczy</h3>
                            <p>bezpośrednio obok</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-3">
                <div class="location-box">
                    <img src="<?=$this->gfxUrl();?>/market.jpg" alt="<?= $this->header['nazwa']; ?>" width="355" height="460">
                    <div class="location-box-shadow">
                        <div class="location-box-info">
                            <h3>Market spożywczy</h3>
                            <p>bezpośrednio obok</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row d-flex justify-content-center">
            <div class="col-3 pl-5">
                <div class="location-box-small">
                    <div class="location-box-icon"><i class="las la-map-marker"></i></div>
                    <h3>Skate Park</h3>
                    <p>120 m</p>
                </div>
            </div>
            <div class="col-3 pl-5">
                <div class="location-box-small">
                    <div class="location-box-icon"><i class="las la-map-marker"></i></div>
                    <h3>Apteka</h3>
                    <p>700 m</p>
                </div>
            </div>
            <div class="col-3 pl-5">
                <div class="location-box-small">
                    <div class="location-box-icon"><i class="las la-map-marker"></i></div>
                    <h3>Dworzec PKP i PKS</h3>
                    <p>1,8 km</p>
                </div>
            </div>
            <div class="col-3 pl-5">
                <div class="location-box-small">
                    <div class="location-box-icon"><i class="las la-map-marker"></i></div>
                    <h3>Poczta</h3>
                    <p>1,2 km</p>
                </div>
            </div>
            <div class="col-3 pl-5">
                <div class="location-box-small">
                    <div class="location-box-icon"><i class="las la-map-marker"></i></div>
                    <h3>Kościół</h3>
                    <p>350 m</p>
                </div>
            </div>
            <div class="col-3 pl-5">
                <div class="location-box-small">
                    <div class="location-box-icon"><i class="las la-map-marker"></i></div>
                    <h3>Siłownia</h3>
                    <p>bezpośrednio obok</p>
                </div>
            </div>
            <div class="col-3 pl-5">
                <div class="location-box-small">
                    <div class="location-box-icon"><i class="las la-map-marker"></i></div>
                    <h3>Autostrada A2</h3>
                    <p>10 km</p>
                </div>
            </div>
            <div class="col-3 pl-5">
                <div class="location-box-small">
                    <div class="location-box-icon"><i class="las la-map-marker"></i></div>
                    <h3>Droga S8</h3>
                    <p>25 km</p>
                </div>
            </div>
            <div class="col-3 pl-5">
                <div class="location-box-small">
                    <div class="location-box-icon"><i class="las la-map-marker"></i></div>
                    <h3>Warszawa</h3>
                    <p>80 km</p>
                </div>
            </div>
            <div class="col-3 pl-5">
                <div class="location-box-small">
                    <div class="location-box-icon"><i class="las la-map-marker"></i></div>
                    <h3>Łódźa</h3>
                    <p>65 km</p>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="mainGallery">
    <div class="container">
        <div class="row d-flex justify-content-center text-center inline">
            <div class="col-12">
                <h2 class="section-title" data-modaltytul="4"><?=$this->getInline($this->inline, 4, 'modaltytul');?></h2>
            </div>
            <div class="col-6">
                <p class="section-title-text" data-modaleditor="4"><?=$this->getInline($this->inline, 4, 'modaleditor');?></p>
            </div>
            <?=$this->inlineModal(4, 'modaltytul,modaleditor', '740,660');?>
            <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
        </div>
    </div>
    <div class="container-fluid mt-5">
        <div class="row gallery-carousel">
            <div class="col-10">
                <img src="https://placehold.co/1280x760" alt="">
                <div class="gallery-apla"><p>Curabitur eget odio in neque tincidunt luctus. Cras ultricies sed libero ut rutrum. Phasellus accumsan mi neque, vestibulum fringilla tortor consequat pharetra.</p></div>
            </div>
            <div class="col-10">
                <img src="https://placehold.co/1280x760" alt="">
                <div class="gallery-apla"><p>Curabitur eget odio in neque tincidunt luctus. Cras ultricies sed libero ut rutrum. Phasellus accumsan mi neque, vestibulum fringilla tortor consequat pharetra.</p></div>
            </div>
            <div class="col-10">
                <img src="https://placehold.co/1280x760" alt="">
                <div class="gallery-apla"><p>Curabitur eget odio in neque tincidunt luctus. Cras ultricies sed libero ut rutrum. Phasellus accumsan mi neque, vestibulum fringilla tortor consequat pharetra.</p></div>
            </div>
            <div class="col-10">
                <img src="https://placehold.co/1280x760" alt="">
                <div class="gallery-apla"><p>Curabitur eget odio in neque tincidunt luctus. Cras ultricies sed libero ut rutrum. Phasellus accumsan mi neque, vestibulum fringilla tortor consequat pharetra.</p></div>
            </div>
        </div>
    </div>
</div>

<div id="mainWhy">
    <div class="container">
        <div class="row d-flex justify-content-center text-center inline">
            <div class="col-12">
                <h2 class="section-title" data-modaltytul="5"><?=$this->getInline($this->inline, 5, 'modaltytul');?></h2>
            </div>
            <div class="col-6">
                <p class="section-title-text" data-modaleditor="5"><?=$this->getInline($this->inline, 5, 'modaleditor');?></p>
            </div>
            <?=$this->inlineModal(5, 'modaltytul,modaleditor', '740,660');?>
            <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
        </div>
        <div class="row">
            <div class="col-12 d-flex flex-wrap justify-content-center">
                <div class="why-box-col">
                    <div class="why-box">
                        <div class="why-box-img">
                            <img src="https://placehold.co/72x72" alt="">
                        </div>
                        <div class="why-box-text">
                            Garaż podziemny
                        </div>
                    </div>
                </div>
                <div class="why-box-col">
                    <div class="why-box">
                        <div class="why-box-img">
                            <img src="https://placehold.co/72x72" alt="">
                        </div>
                        <div class="why-box-text">
                            Stacja ładowania pojazdów elektrycznych
                        </div>
                    </div>
                </div>
                <div class="why-box-col">
                    <div class="why-box">
                        <div class="why-box-img">
                            <img src="https://placehold.co/72x72" alt="">
                        </div>
                        <div class="why-box-text">
                            Winda
                        </div>
                    </div>
                </div>
                <div class="why-box-col">
                    <div class="why-box">
                        <div class="why-box-img">
                            <img src="https://placehold.co/72x72" alt="">
                        </div>
                        <div class="why-box-text">
                            Oświetlenie LED w korytarzach
                        </div>
                    </div>
                </div>
                <div class="why-box-col">
                    <div class="why-box">
                        <div class="why-box-img">
                            <img src="https://placehold.co/72x72" alt="">
                        </div>
                        <div class="why-box-text">
                            Filtry antysmogowe
                        </div>
                    </div>
                </div>
                <div class="why-box-col">
                    <div class="why-box">
                        <div class="why-box-img">
                            <img src="https://placehold.co/72x72" alt="">
                        </div>
                        <div class="why-box-text">
                            5 mieszkań z dużymi ogródkami
                        </div>
                    </div>
                </div>
                <div class="why-box-col">
                    <div class="why-box">
                        <div class="why-box-img">
                            <img src="https://placehold.co/72x72" alt="">
                        </div>
                        <div class="why-box-text">
                            Videodomofony
                        </div>
                    </div>
                </div>
                <div class="why-box-col">
                    <div class="why-box">
                        <div class="why-box-img">
                            <img src="https://placehold.co/72x72" alt="">
                        </div>
                        <div class="why-box-text">
                            Monitoring CCTV
                        </div>
                    </div>
                </div>
                <div class="why-box-col">
                    <div class="why-box">
                        <div class="why-box-img">
                            <img src="https://placehold.co/72x72" alt="">
                        </div>
                        <div class="why-box-text">
                            Rowerownia
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="mainInvestor">
    <div class="container">
        <div class="row inline">
            <div class="col-5">
                <div class="section-img">
                    <img src="<?=$this->getInline($this->inline, 6, 'obrazek');?>" alt="<?=$this->getInline($this->inline, 6, 'obrazek_alt');?>" data-img="6" width="610" height="450">
                </div>
            </div>
            <div class="col-7 d-flex align-items-center">
                <div class="section-text pl-5">
                    <h2 class="section-title" data-modaltytul="6"><?=$this->getInline($this->inline, 6, 'modaltytul');?></h2>
                    <div data-modaleditortext="6">
                        <?=$this->getInline($this->inline, 6, 'modaleditortext');?>
                    </div>
                </div>
            </div>
            <?=$this->inlineModal(6, 'modaltytul,modaleditortext,obrazek,obrazek_alt', '610,450');?>
            <?php //'modaltytul', 'modaleditor', 'modaleditortext', 'modallink', 'obrazek', 'obrazek_alt', 'modallinkbutton' ?>
        </div>
    </div>
</div>