<?php
    if($this->inwestycja->zakres_pokoje || $this->inwestycja->zakres_powierzchnia || $this->inwestycja->zakres_pietra) {
?>
<div id="plansearch">
    <div class="container">
        <div class="row">
            <div class="col-12 p-0">
                <form id="searchOffer" method="get" action="<?php if($this->controller == 'inwestycje-opis'){ echo $this->url(array('tag' => $this->inwestycja->slug), 'inwestycja-plan'); } ?>" class="container">
                    <div class="row">

                        <?php
                        // Inwestycja osiedlowa i budynkowa
                        if($this->inwestycja->typ <> 3) {?>
                            <?php if($this->inwestycja->zakres_pietra) {?>
                                <div class="col">
                                    <label for="s_metry">Piętro</label>
                                    <select name="s_pietro" id="s_pietro">
                                        <option value="">Wszystkie</option>
                                        <?php $var = explode(',', $this->inwestycja->zakres_pietra); ?>
                                        <?php foreach($var as $pozycja) {?>
                                            <option value="<?=$pozycja;?>"<?php if($this->s_pietro && $this->s_pietro == $pozycja){echo ' selected="selected"';};?>><?=$pozycja;?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                            <?php } ?>
                        <?php } ?>

                        <?php if($this->inwestycja->zakres_pokoje){?>
                        <div class="col">
                            <label for="s_pokoje">Pokoje</label>
                            <select name="s_pokoje" id="s_pokoje">
                                <option value="">Wszystkie</option>
                                <?php $var = explode(',', $this->inwestycja->zakres_pokoje); ?>
                                <?php foreach($var as $pozycja) {?>
                                    <option value="<?=$pozycja;?>"<?php if($this->s_pokoje && $this->s_pokoje == $pozycja){echo ' selected="selected"';};?>><?=$pozycja;?></option>
                                <?php } ?>
                            </select>
                        </div>
                        <?php } ?>

                        <div class="col">
                            <label for="s_status">Status</label>
                            <select name="s_status" id="s_status">
                                <option value="">Wszystkie</option>
                                <option value="1"<?php if($this->s_status && $this->s_status == 1){echo ' selected="selected"';};?>>Na sprzedaż</option>
                                <option value="2"<?php if($this->s_status && $this->s_status == 2){echo ' selected="selected"';};?>>Sprzedane</option>
                                <option value="3"<?php if($this->s_status && $this->s_status == 3){echo ' selected="selected"';};?>>Zarezerwowane</option>
                            </select>
                        </div>

                        <?php if($this->inwestycja->zakres_powierzchnia) {?>
                            <div class="col">
                                <label for="s_metry">Powierzchnia</label>
                                <select name="s_metry" id="s_metry">
                                    <option value="">Wszystkie</option>
                                    <?php $var = explode(',', $this->inwestycja->zakres_powierzchnia); ?>
                                    <?php foreach($var as $pozycja) {?>
                                        <option value="<?=$pozycja;?>"<?php if($this->s_metry && $this->s_metry == $pozycja){echo ' selected="selected"';};?>><?=$pozycja;?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        <?php } ?>

                        <div class="col">
                            <label for="s_button" class="empty-label">&nbsp;</label>
                            <input type="hidden" name="a" value="szukaj">
                            <button type="submit" id="s_button" class="bttn m-0 justify-content-center w-100">Szukaj</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<?php } ?>