<div class="title"><h1><?=$this->inwestycja->nazwa;?> - <?=$this->budynek->nazwa;?> - <?=$this->pietro->nazwa;?></h1></div>
<div class="row-fluid">
    <div class="span12">
        <ul class="nav nav-tabs none">
            <li><a href="<?=$this->baseUrl();?>/admin/inwestycje/"><span class="fa i-lista"></span>Lista inwestycji</a></li>
            <li><a href="<?=$this->baseUrl();?>/admin/inwestycje/show/id/<?=$this->inwestycja->id;?>/"><span class="fa i-inwest"></span><?=$this->inwestycja->nazwa;?> - Lista budynków</a></li>
            <li><a href="<?=$this->baseUrl();?>/admin/inwestycje-budynek/show/id/<?=$this->budynek->id;?>/i/<?=$this->inwestycja->id;?>/"><span class="fa i-lista"></span><?=$this->budynek->nazwa;?> - Lista pięter</a></li>
            <li class="active"><span class="fa i-lista"></span><?=$this->pietro->nazwa;?></a></li>
            <li><a href="<?=$this->baseUrl();?>/admin/inwestycje-plan/add/id/<?=$this->inwestycja->id;?>/"><span class="fa i-image"></span>Plan</a></li>
        </ul>

        <div class="widget">
            <div class="table-header"><form action="" id="filter-form">
                    <label>
                        <span>Szukaj:</span><input type="text" size="30" maxlength="30" value="" id="filter" name="filter" />
                    </label>
                </form></div>
            <table width="100%" cellspacing="0" cellpadding="0" class="tableStatic adm" id="sortable">
                <thead>
                <tr>
                    <th width="5%" class="center">Numer</th>
                    <th width="15%">Nazwa</th>
                    <th width="10%">Powierzchnia</th>
                    <th width="10%">Pokoje</th>
                    <th width="10%">Status</th>
                    <th width="40%"></th>
                    <?php if($this->canbetranslate){?><th width="10%"></th><?php } ?>
                </tr>
                </thead>
                <tbody class="content">
                <?php foreach($this->lista as $lista) : ?>
                    <tr id="recordsArray_<?=$this->escape($lista->id);?>">
                        <td class="center"><?=$this->escape($lista->numer);?></td>
                        <td><?=$this->escape($lista->nazwa);?></td>
                        <td><?=$this->escape($lista->metry);?> m<sup>2</sup></td>
                        <td><?=$this->escape($lista->pokoje);?></td>
                        <td><?=$this->roomStatus($lista->status);?></td>
                        <td class="right">
                            <a href="<?=$this->baseUrl();?>/admin/inwestycje-powierzchnia/edit/id/<?=$this->escape($lista->id);?>/typ/<?=$this->escape($lista->typ);?>/p/<?=$this->pietro->id;?>/i/<?=$this->inwestycja->id;?>/<?php if($this->inwestycja->typ == 1) {?>b/<?=$this->budynek->id;?>/<?php } ?>" class="actionBtn tip btnEdit" title="Edytuj"></a>
                            <a href="<?=$this->baseUrl();?>/admin/inwestycje-powierzchnia/delete/id/<?=$this->escape($lista->id);?>/p/<?=$this->pietro->id;?>/i/<?=$this->inwestycja->id;?>/<?php if($this->inwestycja->typ == 1) {?>b/<?=$this->budynek->id;?>/<?php } ?>" class="actionBtn tip btnDelete confirm" title="Usuń"></a>
                        </td>
                        <?php if($this->canbetranslate){?>
                            <td class="right">
                                <?php foreach($this->langs as $lang) { ?>
                                    <a href="<?=$this->baseUrl();?>/admin/inwestycje-powierzchnia/tlumaczenie/id/<?=$this->escape($lista->id);?>/i/<?=$this->inwestycja->id;?>/p/<?=$this->pietro->id;?>/lang/<?=$this->escape($lang->kod);?>/" class="actionBtn tip" title="Edytuj tłumaczenie: <?=$this->escape($lang->nazwa);?>"><img src="<?=$this->baseUrl();?>/public/gfx/flags/<?=$this->escape($lang->flaga);?>"></a>
                                <?php } ?>
                            </td>
                        <?php } ?>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
            <div class="table-footer">
                <?php if($this->pietro->typ == 1) {?>
                    <a href="<?=$this->baseUrl();?>/admin/inwestycje-powierzchnia/add/<?php if($this->inwestycja->typ == 1) {?>b/<?=$this->budynek->id;?>/<?php } ?>i/<?=$this->inwestycja->id;?>/p/<?=$this->pietro->id;?>/typ/1/" class="button greyishBtn">Dodaj mieszkanie</a>
                <?php } ?>

                <?php if($this->pietro->typ == 2) {?>
                    <a href="<?=$this->baseUrl();?>/admin/inwestycje-powierzchnia/add/<?php if($this->inwestycja->typ == 1) {?>b/<?=$this->budynek->id;?>/<?php } ?>i/<?=$this->inwestycja->id;?>/p/<?=$this->pietro->id;?>/typ/2/" class="button greyishBtn">Dodaj lokal usługowy</a>
                <?php } ?>

                <?php if($this->pietro->typ == 3) {?>
                    <a href="<?=$this->baseUrl();?>/admin/inwestycje-powierzchnia/add/<?php if($this->inwestycja->typ == 1) {?>b/<?=$this->budynek->id;?>/<?php } ?>i/<?=$this->inwestycja->id;?>/p/<?=$this->pietro->id;?>/typ/3/" class="button greyishBtn">Dodaj miejsce parkingowe</a>
                <?php } ?>

                <?php if($this->pietro->typ == 4) {?>
                    <a href="<?=$this->baseUrl();?>/admin/inwestycje-powierzchnia/add/<?php if($this->inwestycja->typ == 1) {?>b/<?=$this->budynek->id;?>/<?php } ?>i/<?=$this->inwestycja->id;?>/p/<?=$this->pietro->id;?>/typ/4/" class="button greyishBtn">Dodaj miejsce parkingowe</a>
                <?php } ?>
            </div>
        </div>
    </div>
</div>