<div id="mieszkanie" class="pb-3 pb-md-5">
    <div class="container">
        <?php if($this->inwestycja->typ == 3) { ?>
            <div class="row row-plan-nav">
                <div class="col-12 col-sm-4">
                    <?php if($this->prev_mieszkanie && $this->prev_mieszkanie->numer){?>
                        <a href="<?=$this->url(array(
                            'tag' => $this->inwestycja->slug,
                            'numer' => $this->prev_mieszkanie->numer
                        ), 'inwestycja-domek');?>" class="bttn bttn-sm"><i class="las la-arrow-left"></i> Poprzedni lokal</a>
                    <?php } ?>
                </div>
                <div class="col-12 col-sm-4 text-center">
                    <a href="/#plan" class="bttn bttn-center bttn-sm">Plan inwestycji</a>
                </div>
                <div class="col-12 col-sm-4 text-right">
                    <?php if($this->next_mieszkanie && $this->next_mieszkanie->numer){?>
                        <a href="<?=$this->url(array(
                            'tag' => $this->inwestycja->slug,
                            'numer' => $this->next_mieszkanie->numer
                        ), 'inwestycja-domek');?>" class="bttn bttn-sm">Następny lokal <i class="las la-arrow-right"></i></a>
                    <?php } ?>
                </div>
            </div>
        <?php } ?>

        <div class="row row-mieszkanie">
            <div class="col-12 col-md-8">
                <div class="mieszkanie-dane">
                    <div class="<?=$this->roomStatusTag($this->mieszkanie->status);?>-ap mieszkanie-status">
                        <?=$this->roomStatus($this->mieszkanie->status);?>
                    </div>

                    <ul class="list-unstyled">
                        <li>Pokoje:<span><?=$this->mieszkanie->pokoje;?></span></li>
                        <li>Powierzchnia:<span><?=str_replace('.', '.', $this->mieszkanie->metry);?> m<sup>2</sup></span></li>

                        <li>Poziom:<span><?=$this->mieszkanie->numer_pietro;?></span></li>

                        <?php if($this->mieszkanie->kuchnia){?>
                            <li>Aneks / kuchnia:<span><?=$this->roomKitchen($this->mieszkanie->kuchnia);?></span></li>
                        <?php } ?>
                    </ul>
                    <div class="container-fluid p-0">
                        <div class="row">
                            <div class="col-12 text-center">
                                <?php if($this->mieszkanie->pdf){?><a href="<?=$this->filesUrl(); ?>/inwestycje/pdf/<?=$this->mieszkanie->pdf;?>" title="Pobierz plan mieszkania" class="bttn text-left bttn-pdf mt-3 mt-md-4 mb-4 mb-md-0" target="_blank"><span>Pobierz plan</span></a><?php } ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-4">
                <?php if($this->mieszkanie->plik){?>
                    <div class="mieszkanie-rzut">
                        <a href="<?=$this->filesUrl(); ?>/inwestycje/pomieszczenie/<?=$this->mieszkanie->plik;?>" title="<?=$this->mieszkanie->nazwa;?>"><img src="<?=$this->filesUrl(); ?>/inwestycje/pomieszczenie/<?=$this->mieszkanie->plik;?>" alt="<?=$this->mieszkanie->nazwa;?>"></a>
                    </div>
                <?php } ?>
            </div>
        </div>
        <?php if($this->mieszkanie->tekst){?>
        <div class="row">
            <div class="col-12">
                <div class="mieszkanie-tekst">
                    <?=parse($this->mieszkanie->tekst); ?>
                </div>
            </div>
        </div>
        <?php } ?>
    </div>
</div>

<script src="<?=$this->jsUrl(); ?>/simple-lightbox.jquery.min.js"></script>
<link rel="stylesheet" href="<?=$this->jsUrl(); ?>/simple-lightbox.css">
<script>
    const lightbox = $('.mieszkanie-rzut a').simpleLightbox();
</script>
<?=$this->render('contact/form.phtml');?>
