<div class="title"><h1><?=$this->inwestycja->nazwa;?> - <?=$this->controlname;?></h1></div>
<div class="row-fluid">
    <div class="span12">
        <div class="widget">
            <ul class="nav nav-tabs none">
                <li><a href="<?=$this->baseUrl();?>/admin/inwestycje/"><span class="fa i-lista"></span>Lista inwestycji</a></li>
                <li><a href="<?=$this->baseUrl();?>/admin/inwestycje/show/id/<?=$this->inwestycja->id;?>/"><span class="fa i-inwest"></span><?=$this->inwestycja->nazwa;?></a></li>
                <li class="active"><span class="fa i-image"></span>Plan</li>
            </ul>

            <div class="table-header" style="padding:5px">
                <div class="info">Rzut inwestycji: <b><?=$this->planszerokosc;?>px</b> szerokości / <b><?=$this->planwysokosc;?>px</b> wysokości</div>
                <?php if($this->plan && $this->plan->plik){?>
                    <div id="budynek">
                        <img src="<?=$this->baseUrl();?>/files/inwestycje/plan/<?=$this->plan->plik;?>" alt="">
                    </div>
                <?php } ?>
            </div>

            <div class="table-footer">
                <div id="jquery-wrapped-fine-uploader"></div>
            </div>
        </div>
    </div>
</div>
<script src="<?=$this->baseUrl();?>/public/js/fineuploader.js" type="text/javascript"></script>
<script type="text/javascript" language="javascript">
    //<![CDATA[
    $(document).ready(function(){
        let fileCount = 0;
        $('#jquery-wrapped-fine-uploader').fineUploader({
            debug: true,
            text: {
                uploadButton:'<div>Zmień obrazek inwestycji</div>'
            },
            request: {
                endpoint: '<?=$this->baseUrl();?>/admin/inwestycje-plan/upload/id/<?=$this->inwestycja->id;?>/'
            }
        }).on('error', function(event, id, name, reason) {
        })
            .on('submit', function(id, nameN){
                fileCount++;
            })
            .on('complete', function(event, id, name, response){
                if(response.success===true){
                    fileCount--;
                    if(fileCount === 0){
                        location.reload();
                    }
                }
            });
    });
    //]]>
</script>