<div class="title"><h1><?=$this->controlname;?></h1></div>
<div class="row-fluid">
	<div class="span12">
		<ul class="nav-tabs none">
			<li class="active"><a href="<?=$this->baseUrl();?>/admin/inwestycje/"><span class="fa i-lista"></span>Lista inwestycji</a></li>
		</ul>
		<div class="widget">
			<div class="table-header"><form action="" id="filter-form">
			<label>
			<span>Szukaj:</span><input type="text" size="30" maxlength="30" value="" id="filter" name="filter" />
			</label>
			</form></div>
			<table width="100%" cellspacing="0" cellpadding="0" class="tableStatic adm" id="sortable">
				<thead>
					<tr>
					<th width="5%" style="text-align:center">ID</th>
					<th width="30%">Nazwa</th>
					<th width="20%" class="center">Status</th>
					<th width="15%" class="center">Typ</th>
					<th width="10%" class="center">Data utworzenia</th>
					<th width="10%" class="center">Data edycji</th>
					<th width="10%"></th>
                    <?php if($this->canbetranslate){?><th width="10%"></th><?php } ?>
					</tr>
				</thead>
				<tbody class="content">
				<?php foreach($this->lista as $l) : ?>
				<tr id="recordsArray_<?= $this->escape($l->id);?>">
					<td class="center"><?=$this->escape($l->id);?></td>
					<td><a href="<?=$this->baseUrl();?>/admin/inwestycje/show/id/<?=$this->escape($l->id);?>/"><?=$this->escape($l->nazwa);?></a></td>
					<td class="center"><span class="inweststat-<?=$l->status;?> typ-<?=$l->typ;?>"><?=statusInwestycji($l->status);?></span></td>
					<td class="center"><?=typ($l->typ);?></td>
					<td class="center"><?=$this->escape($l->data_dodania);?></td>
					<td class="center"><?=$this->escape($l->data_edycji);?></td>
					<td class="right">
					<?php if($l->typ <> 4){?>
					<a href="<?=$this->baseUrl();?>/admin/inwestycje-plan/add/id/<?=$this->escape($l->id);?>/" class="actionBtn tip btnImage" title="Pokaż plan inwestycji"></a><?php } ?>
					<a href="<?=$this->baseUrl();?>/admin/inwestycje/show/id/<?=$this->escape($l->id);?>/" class="actionBtn tip btnCatalog" title="Pokaż inwestycję"></a>
                    <a href="<?=$this->baseUrl();?>/admin/inwestycje/edit/id/<?=$this->escape($l->id);?>/" class="actionBtn tip btnEdit" title="Edytuj"></a>
					</td>
                    <?php if($this->canbetranslate){?>
                        <td class="right">
                            <?php foreach($this->langs as $lang) { ?>
                                <a href="<?=$this->baseUrl();?>/admin/inwestycje/tlumaczenie/id/<?=$this->escape($l->id);?>/lang/<?=$this->escape($lang->kod);?>/" class="actionBtn tip" title="Edytuj tłumaczenie: <?=$this->escape($lang->nazwa);?>"><img src="<?=$this->baseUrl();?>/public/gfx/flags/<?=$this->escape($lang->flaga);?>"></a>
                            <?php } ?>
                        </td>
                    <?php } ?>
				</tr>
				<?php endforeach; ?>
				</tbody>
			</table>
		</div>
	</div>
</div>
<script type="text/javascript">
//<![CDATA[
$(document).ready(function(){
	$(".content").sortuj('<?=$this->baseUrl();?>/admin/inwestycje/ustaw/co/inwestycje/');
});
//]]>
</script>