<div class="title"><h1><?=$this->inwestycja->nazwa;?></h1></div>
<div class="row-fluid">
	<div class="span12">
	<ul class="nav nav-tabs none">
		<li><a href="<?=$this->baseUrl();?>/admin/inwestycje/"><span class="fa i-lista"></span>Lista inwestycji</a></li>
		<li class="active"><a href="<?=$this->baseUrl();?>/admin/inwestycje/show/id/<?=$this->inwestycja->id;?>/"><span class="fa i-inwest"></span><?=$this->inwestycja->nazwa;?></a></li>
		<li><a href="<?=$this->baseUrl();?>/admin/inwestycje-plan/add/id/<?=$this->inwestycja->id;?>/"><span class="fa i-image"></span>Plan</a></li>
	</ul>

		<div class="widget">
			<div class="table-header"><form action="" id="filter-form">
			<label>
			<span>Szukaj:</span><input type="text" size="30" maxlength="30" value="" id="filter" name="filter" />
			</label>
			</form></div>
			
			<?php if($this->inwestycja->typ == 1){?>
			<table width="100%" cellspacing="0" cellpadding="0" class="tableStatic adm" id="sortable">
				<thead>
					<tr>
					<th width="20%">Nazwa</th>
					<th width="35%">Numer</th>
					<th width="35%">Kolejność</th>
					<th width="10%"></th>
                    <?php if($this->canbetranslate){?><th width="10%"></th><?php } ?>
					</tr>
				</thead>
				<tbody class="content">
				<?php foreach($this->lista as $lista) : ?>
				<tr id="recordsArray_<?=$this->escape($lista->id);?>">
				<td><a href="<?=$this->baseUrl();?>/admin/inwestycje-budynek/show/id/<?=$this->escape($lista->id);?>/i/<?=$this->inwestycja->id;?>/" class="tip" title="Pokaż budynek"><?=$this->escape($lista->nazwa);?></a></td>
				<td><?=$this->escape($lista->numer);?></td>
				<td><?=$this->escape($lista->numer_lista);?></td>
				<td class="right">
				    <a href="<?=$this->baseUrl();?>/admin/inwestycje-budynek/show/id/<?=$this->escape($lista->id);?>/i/<?=$this->inwestycja->id;?>/" class="actionBtn tip btnCatalog" title="Pokaż budynek"></a>
                    <a href="<?=$this->baseUrl();?>/admin/inwestycje-budynek/edit/id/<?=$this->escape($lista->id);?>/i/<?=$this->inwestycja->id;?>/" class="actionBtn tip btnEdit" title="Edytuj"></a>
                    <a href="<?=$this->baseUrl();?>/admin/inwestycje-budynek/delete/id/<?=$this->escape($lista->id);?>/i/<?=$this->inwestycja->id;?>/" class="actionBtn tip btnDelete confirm" title="Usuń"></a>
				</td>
                <?php if($this->canbetranslate){?>
                    <td class="right">
                        <?php foreach($this->langs as $lang) { ?>
                            <a href="<?=$this->baseUrl();?>/admin/inwestycje-budynek/tlumaczenie/id/<?=$this->escape($lista->id);?>/lang/<?=$this->escape($lang->kod);?>/i/<?=$this->inwestycja->id;?>/" class="actionBtn tip" title="Edytuj tłumaczenie: <?=$this->escape($lang->nazwa);?>"><img src="<?=$this->baseUrl();?>/public/gfx/flags/<?=$this->escape($lang->flaga);?>"></a>
                        <?php } ?>
                    </td>
                <?php } ?>
				</tr>
				<?php endforeach; ?>
				</tbody>
			</table>
			
<script type="text/javascript" language="javascript">
//<![CDATA[
$(document).ready(function(){
	$(".content").sortuj('<?=$this->baseUrl();?>/admin/inwestycje-budynek/ustaw/co/inwestycje_budynki/');
});
//]]>
</script>
			<?php } ?>
			
			<?php if($this->inwestycja->typ == 2){?>
			<table width="100%" cellspacing="0" cellpadding="0" class="tableStatic adm" id="sortable">
				<thead>
					<tr>
					<th width="20%">Nazwa</th>
					<th width="35%">Numer</th>
					<th width="35%">Kolejność</th>
					<th width="10%"></th>
                    <?php if($this->canbetranslate){?><th width="10%"></th><?php } ?>
					</tr>
				</thead>
				<tbody class="content">
				<?php foreach($this->lista as $lista) : ?>
				<tr>
				<td><a href="<?=$this->baseUrl();?>/admin/inwestycje-pietro/show/id/<?=$this->escape($lista->id);?>/i/<?=$this->inwestycja->id;?>/" class="tip" title="Pokaż piętro"><?=$this->escape($lista->nazwa);?></a></td>
				<td><?=$this->escape($lista->numer);?></td>
				<td><?=$this->escape($lista->numer_lista);?></td>
				<td class="right">
				    <a href="<?=$this->baseUrl();?>/admin/inwestycje-pietro/show/id/<?=$this->escape($lista->id);?>/i/<?=$this->inwestycja->id;?>/" class="actionBtn tip btnCatalog" title="Pokaż piętro"></a>
                    <a href="<?=$this->baseUrl();?>/admin/inwestycje-pietro/edit/id/<?=$this->escape($lista->id);?>/i/<?=$this->inwestycja->id;?>/" class="actionBtn tip btnEdit" title="Edytuj"></a>
                    <a href="<?=$this->baseUrl();?>/admin/inwestycje-pietro/delete/id/<?=$this->escape($lista->id);?>/i/<?=$this->inwestycja->id;?>/" class="actionBtn tip btnDelete confirm" title="Usuń"></a>
                    <!--<a href="<?=$this->baseUrl();?>/admin/inwestycje-pietro/copy/id/<?=$this->escape($lista->id);?>/i/<?=$this->inwestycja->id;?>/" class="actionBtn tip btnCopy" title="Kopiuj pietro"></a>-->
				</td>
                <?php if($this->canbetranslate){?>
                    <td class="right">
                        <?php foreach($this->langs as $lang) { ?>
                            <a href="<?=$this->baseUrl();?>/admin/inwestycje-pietro/tlumaczenie/id/<?=$this->escape($lista->id);?>/lang/<?=$this->escape($lang->kod);?>/i/<?=$this->inwestycja->id;?>/" class="actionBtn tip" title="Edytuj tłumaczenie: <?=$this->escape($lang->nazwa);?>"><img src="<?=$this->baseUrl();?>/public/gfx/flags/<?=$this->escape($lang->flaga);?>"></a>
                        <?php } ?>
                    </td>
                <?php } ?>
				</tr>
				<?php endforeach; ?>
				</tbody>
			</table>
			<?php } ?>
			
			<?php if($this->inwestycja->typ == 3){?>
			<table width="100%" cellspacing="0" cellpadding="0" class="tableStatic adm" id="sortable">
				<thead>
					<tr>
						<th width="5%" class="center">Numer</th>
						<th width="55%">Nazwa</th>
						<th width="10%">Powierzchnia</th>
						<th width="10%">Status</th>
						<th width="10%"></th>
                        <?php if($this->canbetranslate){?><th width="10%"></th><?php } ?>
					</tr>
				</thead>
				<tbody class="content">
				<?php foreach($this->lista as $lista) : ?>
				<tr id="recordsArray_<?=$this->escape($lista->id);?>">
				<td class="center"><?=$this->escape($lista->numer);?></td>
				<td><?=$this->escape($lista->nazwa);?></td>
				<td><?=$this->escape($lista->metry);?> m<sup>2</sup></td>
				<td><?=$this->roomStatus($lista->status);?></td>
				<td class="right">
				    <a href="<?=$this->baseUrl();?>/admin/inwestycje-powierzchnia/edit/id/<?=$this->escape($lista->id);?>/i/<?=$this->inwestycja->id;?>/" class="actionBtn tip btnEdit" title="Edytuj"></a>
				    <a href="<?=$this->baseUrl();?>/admin/inwestycje-powierzchnia/delete/id/<?=$this->escape($lista->id);?>/i/<?=$this->inwestycja->id;?>/" class="actionBtn tip btnDelete confirm" title="Usuń"></a>
				</td>
                <?php if($this->canbetranslate){?>
                    <td class="right">
                        <?php foreach($this->langs as $lang) { ?>
                            <a href="<?=$this->baseUrl();?>/admin/inwestycje-powierzchnia/tlumaczenie/id/<?=$this->escape($lista->id);?>/lang/<?=$this->escape($lang->kod);?>/i/<?=$this->inwestycja->id;?>/" class="actionBtn tip" title="Edytuj tłumaczenie: <?=$this->escape($lang->nazwa);?>"><img src="<?=$this->baseUrl();?>/public/gfx/flags/<?=$this->escape($lang->flaga);?>"></a>
                        <?php } ?>
                    </td>
                <?php } ?>
				</tr>
				<?php endforeach; ?>
				</tbody>
			</table>
			<?php } ?>
			
			<div class="table-footer">
				<?php if($this->inwestycja->typ == 1){?>
				    <a href="<?=$this->baseUrl();?>/admin/inwestycje-budynek/add/i/<?=$this->inwestycja->id;?>/" class="button greyishBtn">Dodaj budynek</a>
				<?php } ?>
				<?php if($this->inwestycja->typ == 2){?>
				    <a href="<?=$this->baseUrl();?>/admin/inwestycje-pietro/add/i/<?=$this->inwestycja->id;?>/" class="button greyishBtn">Dodaj piętro</a>
				<?php } ?>
				<?php if($this->inwestycja->typ == 3){?>
				    <a href="<?=$this->baseUrl();?>/admin/inwestycje-powierzchnia/add/i/<?=$this->inwestycja->id;?>/" class="button greyishBtn">Dodaj dom</a>
				<?php } ?>
			</div>
		</div>
	</div>
</div>