<div class="title"><h1><?=$this->inwestycja->nazwa;?> - <?=$this->budynek->nazwa;?></h1></div>
<div class="row-fluid">
    <div class="span12">
        <ul class="nav nav-tabs none">
            <li><a href="<?=$this->baseUrl();?>/admin/inwestycje/"><span class="fa i-lista"></span>Lista inwestycji</a></li>
            <li><a href="<?=$this->baseUrl();?>/admin/inwestycje/show/id/<?=$this->inwestycja->id;?>/"><span class="fa i-inwest"></span><?=$this->inwestycja->nazwa;?> - Lista budynków</a></li>
            <li class="active"><a href="<?=$this->baseUrl();?>/admin/inwestycje-budynek/show/id/<?=$this->budynek->id;?>/i/<?=$this->inwestycja->id;?>/"><span class="fa i-lista"></span><?=$this->budynek->nazwa;?> - Lista pięter</a></li>
            <li><a href="<?=$this->baseUrl();?>/admin/inwestycje-plan/add/id/<?=$this->inwestycja->id;?>/"><span class="fa i-image"></span>Plan</a></li>
        </ul>

        <div class="widget">
            <div class="table-header"><form action="" id="filter-form">
                    <label>
                        <span>Szukaj:</span><input type="text" size="30" maxlength="30" value="" id="filter" name="filter" />
                    </label>
                </form></div>
            <table width="100%" cellspacing="0" cellpadding="0" class="tableStatic adm" id="sortable">
                <thead>
                <tr>
                    <th width="20%">Nazwa</th>
                    <th width="30%">Numer</th>
                    <th width="30%" class="text-center">Kolejność</th>
                    <th width="10%"></th>
                    <?php if($this->canbetranslate){?><th width="10%"></th><?php } ?>
                </tr>
                </thead>
                <tbody class="content">
                <?php foreach($this->floors as $f) : ?>
                    <tr>
                        <td><a href="<?=$this->baseUrl();?>/admin/inwestycje-budynek-pietro/show/id/<?=$this->escape($f->id);?>/i/<?=$this->inwestycja->id;?>/b/<?=$this->budynek->id;?>/" class="tip" title="Pokaż piętro"><?=$this->escape($f->nazwa);?></a></td>
                        <td class="text-center"><?=$this->escape($f->numer);?></td>
                        <td class="text-center"><?=$this->escape($f->numer_lista);?></td>
                        <td class="right">
                            <a href="<?=$this->baseUrl();?>/admin/inwestycje-budynek-pietro/show/id/<?=$this->escape($f->id);?>/i/<?=$this->inwestycja->id;?>/b/<?=$this->budynek->id;?>/" class="actionBtn tip btnCatalog" title="Pokaż piętro"></a>
                            <a href="<?=$this->baseUrl();?>/admin/inwestycje-budynek-pietro/edit/id/<?=$this->escape($f->id);?>/i/<?=$this->inwestycja->id;?>/b/<?=$this->budynek->id;?>/" class="actionBtn tip btnEdit" title="Edytuj"></a>
                            <a href="<?=$this->baseUrl();?>/admin/inwestycje-budynek-pietro/delete/id/<?=$this->escape($f->id);?>/i/<?=$this->inwestycja->id;?>/b/<?=$this->budynek->id;?>/" class="actionBtn tip btnDelete confirm" title="Usuń"></a>
                        </td>
                        <?php if($this->canbetranslate){?>
                            <td class="right">
                                <?php foreach($this->langs as $lang) { ?>
                                    <a href="<?=$this->baseUrl();?>/admin/inwestycje-budynek-pietro/tlumaczenie/id/<?=$this->escape($f->id);?>/i/<?=$this->inwestycja->id;?>/b/<?=$this->budynek->id;?>/lang/<?=$this->escape($lang->kod);?>/" class="actionBtn tip" title="Edytuj tłumaczenie: <?=$this->escape($lang->nazwa);?>"><img src="<?=$this->baseUrl();?>/public/gfx/flags/<?=$this->escape($lang->flaga);?>"></a>
                                <?php } ?>
                            </td>
                        <?php } ?>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
            <div class="table-footer">
                <a href="<?=$this->baseUrl();?>/admin/inwestycje-budynek-pietro/add/i/<?=$this->inwestycja->id;?>/b/<?=$this->budynek->id;?>/" class="button greyishBtn">Dodaj piętro</a>
            </div>
        </div>
    </div>
</div>