<footer>
    <div id="footer">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-3 col-lg-2">
                    <div id="logo">
                        <a href="<?=$this->baseUrl;?>/">
                            <img src="<?=$this->gfxUrl();?>/logo.svg" alt="<?= $this->header['nazwa']; ?>" width="236" height="193">
                        </a>
                    </div>
                </div>
                <div class="col-12 col-md-9 col-lg-10 col-xl-7 d-flex align-items-center">
                    <div class="footer-text">
                        <p>EPS Development Spółka z ograniczoną odpowiedzialnością z siedzibą w Skierniewicach, wpisana do Rejestru Przedsiębiorców prowadzonego przez Sąd Rejonowy dla Łodzi Śródmieścia w Łodzi, XX Wydział Krajowego Rejestru Sądowego, pod nr. KRS: 0000905123</p>
                        <p>REGON: 389216974</p>
                        <p>NIP 836-187-69-01</p>
                        <p>Z pokrytym w całości kapitałem zakładowym wynoszącym  337.500,00 zł.</p>
                    </div>
                </div>
                <div class="col-12 col-xl-1 d-flex align-items-center">
                    <div class="footer-menu text-center text-xl-left">
                        <ul class="mb-0 list-unstyled">
                            <li><a href="">O inwestycji</a></li>
                            <li><a href="">Mieszkania</a></li>
                            <li><a href="">Lokalizacja</a></li>
                            <li><a href="">Galeria</a></li>
                            <li><a href="">Inwestor</a></li>
                            <li><a href="">Finansowanie</a></li>
                            <li><a href="">Kontakt</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-12 col-xl-2 d-flex align-items-end justify-content-end">
                    <div class="footer-copyright text-center text-xl-right">
                        <p>Realizacja: <a href="">4Dl.pl</a></p>
                        <p>Powered by: <a href="">DeveloPro.pl</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="footer-content">
                    <p>Informujemy, że wszelkie elementy zielone, rzeczy ruchome, wygląd zewnętrzny budynków oraz sposób zagospodarowania nieruchomości i nieruchomości sąsiednich, przedstawione na stronie www.artlocum.pl, mają charakter poglądowy i stanowią jedynie ogólny, przewidywany sposób wykonania inwestycji. Oznacza to, że wizualizacje nie przedstawiają ostatecznych, docelowych właściwości inwestycji wraz z najbliższym otoczeniem i tym samym nie stanowią próbki lub wzoru w rozumieniu art. 5561 § 1k.c. Sposób wykonania inwestycji, w tym zagospodarowania nieruchomości wspólnej/jej części oraz nieruchomości sąsiednich może się w pewnym zakresie zmienić. Szczegółowe i wiążące informacje dotyczące nabywanych nieruchomości zawarte są w umowie przedwstępnej oraz projekcie architektoniczno–budowlanym, który pozostaje do wglądu dla zainteresowanych nabywców w siedzibie oddziału spółki realizującej sprzedaż lokali.</p>
                </div>
            </div>
        </div>
    </div>
</footer>

<div id="cookies"><p><a href="" class="closecookies gradient">Zamknij</a><?= $this->header['cookies']; ?></p></div>

<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&family=Poppins:wght@300;400;600;700&display=swap" rel="stylesheet">