<div id="pageheader">
    <div class="container h-100">
        <div class="row h-100 d-flex align-items-center">
            <div class="col-12 text-center">
                <?php if($this->strona_h1){ ?>
                    <h1><?=$this->strona_h1;?></h1>
                <?php } else { ?>
                    <h1><?=$this->strona_nazwa;?></h1>
                <?php } ?>
            </div>
        </div>
    </div>
</div>